# -*- coding: utf-8 -*-
"""Build a dry-run Ollama/WorkOS sign-up request from reversed evidence.

Default mode is OFFLINE/DRY-RUN: it prints the HTTP shape and curl skeleton only.
It does not solve Turnstile and does not submit registration.
"""
from __future__ import annotations

import argparse
import json
import shlex
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "exports" / "ollama_signup_flow_precise.json"
CLIENT_ID = "client_01JX0QMHD43PFFCCNXH82A6K8B"
REDIRECT_URI = "https://ollama.com/auth/callback"
BASE_URL = "https://signin.ollama.com/sign-up"


def ps_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--email", default="user@example.com")
    ap.add_argument("--sid", default="<fresh_authorization_session_id>")
    ap.add_argument("--signals", default="<base64(JSON.stringify(radarSignals))>")
    ap.add_argument("--turnstile-token", default="<cf_turnstile_token>")
    ap.add_argument("--format", choices=["json", "curl-powershell"], default="json")
    args = ap.parse_args()

    evidence = json.loads(EVIDENCE.read_text(encoding="utf-8")) if EVIDENCE.exists() else {}
    action = (evidence.get("flight_action_ids") or ["409e88ace8f865462142c9b1ba39df1fcdfd4c8957"])[0]
    url = f"{BASE_URL}?client_id={CLIENT_ID}&redirect_uri=https%3A%2F%2Follama.com%2Fauth%2Fcallback&authorization_session_id={args.sid}"
    fields = {
        "email": args.email,
        "intent": "sign-up",
        "redirect_uri": REDIRECT_URI,
        "authorization_session_id": args.sid,
        "state": "",
        "signals": args.signals,
        "bot_detection_token": args.turnstile_token,
    }
    req = {
        "warning": "dry-run only; do not submit to production without authorization/test account",
        "method": "POST",
        "url": url,
        "headers": {
            "Next-Action": action,
            "Origin": "https://signin.ollama.com",
            "Referer": url,
            "Accept": "*/*",
        },
        "multipart_fields": fields,
        "required_runtime_values": [
            "fresh authorization_session_id from same browser session",
            "__wuid cookie from signFingerprint",
            "signals generated by Radar hook",
            "bot_detection_token from Cloudflare Turnstile siteKey 0x4AAAAAAAMNIvC45A4Wjjln",
        ],
    }
    if args.format == "json":
        print(json.dumps(req, indent=2, ensure_ascii=False))
    else:
        parts = ["curl.exe", "-i", "-X", "POST", ps_quote(url)]
        for k, v in req["headers"].items():
            parts += ["-H", ps_quote(f"{k}: {v}")]
        for k, v in fields.items():
            parts += ["-F", ps_quote(f"{k}={v}")]
        print(" \\\n  ".join(parts))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
